// skyeScene.js
// Location: js/game/scenes/locations/skye/skyeScene.js
//
// Base class for the Isle of Skye training grounds (Dún Scáith and
// surroundings). Replaces the old standalone BowTutorial scene, which will
// stay registered until this island is playable end to end.
//
// Built on BogScene so it gets content loading (.dlg-compiled NPCs and
// fixed encounters), exits/entries, wallMask, ForestEffects etc. for free.
// Differences from the bog:
//   • maps live in  public/maps/skyeMaps/
//   • content in    public/data/skye/   (skye_cladach -> skyeCladach.js)
//   • no random encounter deck -- everything on Skye is placed by hand
//   • sea tiles are unwalkable
//
// LAYOUT (north = further from the camera):
//
//          skye_dun          Dún Scáith -- Scáthach, archery
//             |
//        skye_droichead      Droichead na Léimeanna -- the gate
//             |
//        skye_machaire ---- skye_faiche   (sparring green, combat later)
//             |
//         skye_cladach       the shore -- landing, boat, Conall
//
// Terrain for all five is generated by
//   node tools/map-editor/generators/skye_gen.mjs

import BogScene from '../bogScene.js'
import FightLens from '../../../combat/fightLens.js'

// Synthetic GIDs for Skye figures (billboard, moon badge and card portrait
// all resolve through these). 91xx are taken by the mainland NPCs.
// Keep in sync with visual.gid in public/data/skye/*.js.
export const SKYE_GID = {
  UATHACH: 9201,
  BOAT:    9202,   // badge/portrait only; ShoreProps draws the boat itself
  WARDEN:  9203,   // the sparring partner on the faiche (skyeFaiche.js)
  OGHAM:   9204,   // (unused: the cladach engravings draw their own chisel icon, wallEngravings.js)
}

// Art per figure. PLACEHOLDERS until real sprites exist.
const SKYE_ART = {
  [SKYE_GID.UATHACH]: '/assets/npcs/sorcha.png',
  [SKYE_GID.BOAT]:    '/assets/boat.png',
  [SKYE_GID.WARDEN]:  '/assets/npcs/othran.png',
}

// Hearts come back on their own on Skye, one every REGEN_MS, while you're
// not en garde -- the wooden blade bruises, it doesn't wound.
const REGEN_MS = 6000

// left behind when you land on Skye (see _stripPack)
const ISLAND_NO = new Set(['simple_bow', 'arrows', 'healing_potion'])

export default class SkyeScene extends BogScene {
  getMapPath()            { return `/maps/skyeMaps/${this.getMapKey()}.json?v=${Date.now()}` }
  getNeighborMapPath(key) { return `/maps/skyeMaps/${key}.json?v=${Date.now()}` }
  getContentDir()         { return 'skye' }

  getAmbient()     { return 0x2a3438 }
  getPlayerLight() { return { color: 0xfff5dd, intensity: 2.0, radius: 320 } }
  getSkyImage()    { return '/assets/skies/skye.png' }
  // dialogue cards set their English in the return crossing's style (textPanel.js)
  get englishInk() { return true }
  // a painting: shown whole, standing on the horizon, not drifting (pgrSky.js)
  skyFitsHorizon() { return true }
  // The painted sky doesn't work well with tilt shift blur -- it diminishes the
  // scene -- so at rest there is none: no blur, haze or vignette. It comes up
  // only in dialogue (textPanel.js, skyeCaption.speak), when the world blurs
  // round whoever is speaking.
  getTiltShift() {
    return {
      focusY: 0.62, focusHeight: 0.20,
      farBlur: 0, nearBlur: 0, hazeAmount: 0, vignette: 0,
      combat: { focusHeight: 0.22, farBlur: 5, nearBlur: 3, farHold: 0.6, nearHold: 0.5, vignette: 0.30, dim: 0, saturate: 1.08, follow: true },
      dialogue: { focusHeight: 0.12, farBlur: 9, nearBlur: 7, farHold: 0.7, nearHold: 0.7, vignette: 0.36, dim: 0.22, saturate: 1.12, follow: true },
    }
  }
  getMusicTrack()  { return null }

  // Sea, plus the bushes and rocks that stand in for brambles and
  // chevaux de frise until there's real art. Skye only: on the mainland
  // these stay walkable scenery.
  getExtraUnwalkableGIDs() {
    return new Set([1625, 1679, 44, 45, 46, 47, 48, 154, 155, 156])
  }

  // create() is async, so anything thrown inside it becomes an unhandled
  // promise rejection -- which the in-page console does not show, leaving
  // a black screen and a clean log. Catch and print it instead.
  async create(data) {
    try {
      await super.create(data)
    } catch (e) {
      console.error(`[${this.scene.key}] create threw:`, e?.message)
      console.error(e?.stack)
      return
    }
    for (const [gid, url] of Object.entries(SKYE_ART)) {
      this.perspectiveGround?.registerCustomTile?.(Number(gid), url)
    }
    this._stripPack()
  }

  // On the island you train with what you're given: no bow, no arrows, no
  // potion in your pack (the pack is rebuilt with each scene, so this is
  // done on every arrival). What a champion starts the main game with is
  // still to be decided.
  _stripPack() {
    const inv = this.player?.inventory
    if (!inv?.slots) return
    inv.slots.forEach((it, i) => { if (it && ISLAND_NO.has(it.id)) inv.slots[i] = null })
    this.player.updateStatsFromEquipment?.()
  }

  // Collision masks with no GID behind them:
  //   hedgeMask -- hedges, drawn by Vegetation (gorse + bramble)
  //   blockMask -- solid rock, e.g. the skirt round a pedestal
  isColliding(x, y) {
    const ts = this.tileSize
    const tx = Math.floor(x / ts), ty = Math.floor(y / ts)
    if (this.mapData?.hedgeMask?.[ty]?.[tx]) return true
    if (this.mapData?.blockMask?.[ty]?.[tx]) return true
    return super.isColliding(x, y)
  }

  // No random encounter cards on Skye.
  _placeEncounterDeck() {}

  // ── in conversation: blade away, camera in on the speaker ────────────────
  // (the moon then shows the English instead of striking; FightLens reads
  // lensFocus/lensSolo -- the same close-in as a bout)
  _talkTile() {
    if (this._speakTile) return this._speakTile                       // a spoken caption (skyeCaption.speak)
    const z = this._encounterPanel?._isOpen ? this._encounterPanel._active : null
    const lx = z?.getData?.('logicalX'), ly = z?.getData?.('logicalY')
    if (lx == null) return null
    const ts = this.tileSize
    return [Math.round((lx - ts / 2) / ts), Math.round((ly - ts / 2) / ts)]
  }
  lensFocus() { return this._talkTile() }
  lensSolo() { return !!this._talkTile() }
  // scenes without a bout have no lens of their own: a bare one for conversations
  _talkLensTick(delta) {
    if (this._melee?.lens || !this.perspectiveGround) return
    if (!this._talkLens) {
      this._talkLens = new FightLens(this, { noFoe: true, combat: false, bout: { over: false } })
      this.events?.once?.('shutdown', () => { this._talkLens?.destroy(); this._talkLens = null })
    }
    this._talkLens.update(delta)
  }
  _sheatheToTalk() {
    const m = this._melee?.melee
    if (m?.enGarde && (this._encounterPanel?._isOpen || this.textPanel?.isVisible)) m.setEnGarde(false)
  }

  update(time, delta) {
    super.update(time, delta)
    this._sheatheToTalk()
    this._talkLensTick(delta)
    const p = this.player
    if (!p || this._moonOwner?.enGarde || p.currentHP >= p.maxHP || p.currentHP <= 0) { this._regenMs = 0; return }
    this._regenMs = (this._regenMs || 0) + delta
    if (this._regenMs >= REGEN_MS) { this._regenMs = 0; p.heal(1) }
  }
}
