// plates.js
// Location: js/game/scenes/locations/bog/plates.js
//
// A capture level: not part of the game, a photographic studio for the intro's
// backdrop plates. Open it with  ?scene=plates  and take screenshots.
//
//   ?scene=plates              the map as the game renders it (real sky, haze)
//   ?scene=plates&key=1        chroma mode: the sky becomes flat magenta and the
//                              haze and vignette come off, so Color to Alpha in
//                              GIMP cuts the silhouettes out cleanly. The
//                              depth-of-field blur stays, on purpose: that soft
//                              focus is part of the look being borrowed.
//   ?scene=plates&ui=0         start with the interface hidden. Either way, tap
//                              the top-left corner to show/hide it.
//
//   &band=far|mid|near|all     [bandMaps] which level: far = rugged mountains, mid = a hilltop
//                              (the ground behind it left empty), near = meadow and flowers,
//                              all (the default) = the three together, as a preview. Each
//                              band is its own map so every layer can be shot COMPLETE.
//   &flora=0|1                [floraSwitch] the game's wildflowers. Default OFF for near, far
//                              and mid (the near plate is shot as ground only; the flowers get
//                              regrown live in the intro so they keep their sway). ON for `all`.
//   &night=1                  [nightGrade] a moonlit colour grade on the world layers
//                              (0..1 is the intensity; the magenta key colour is untouched)
//   &horizon=0.10              where the horizon sits (game default 0.28). Lower = a taller
//                              ground area, and room for tall mountains before the clip
//   &across=2.5                tiles across the screen (game default 3.8). Lower = bigger
//   (horizon and across also pin the camera: terrain avoidance is switched off)
//
// The map is generated by tools/map-editor/generators/plates_gen.mjs (retune the
// BANDS there, re-run, reload). No NPCs, no encounters, no exits.

import PerspectiveScene from '../perspectiveScene.js'
import SteepFaceRenderer from '../../../effects/steepFaceRenderer.js'

const KEY_COLOUR = '#ff00ff'

/* [nightGrade] The moonlit grade at full strength: saturation to 55%, then a
   per-channel gain (red held down hardest, blue least) and a small blue lift in
   the shadows so blacks aren't dead. Tuned on a real capture of this level; the
   numbers are in sRGB, matching the filter's color-interpolation-filters. */
const NIGHT = { sat: 0.55, slope: [0.30, 0.42, 0.62], lift: [0.010, 0.020, 0.055] }
const NIGHT_LAYERS = ['pgr-ground', 'steep-face-overlay', 'pgr-objects', 'pgr-sky-img', 'pgr-mountain-img']

/* [bandMaps] The levels, and the horizon each wants by default. The mountains are tall
   enough that the game's own horizon (0.28) would cut them flat; 0.10 leaves room.
   An explicit &horizon= always wins. `near` is flat, so it keeps the game's own view. */
const BANDS = ['all', 'far', 'mid', 'near']
const BAND_HORIZON = { all: 0.10, far: 0.10, mid: 0.10, near: null }

export default class PlatesScene extends PerspectiveScene {

  // [bandMaps] The game paints stone on camera-facing slopes steeper than 70% of this
  // (its default is 0.6, so 0.42). That is right for the game's own hills, which never
  // pass ~2 units, but it would turn the hilltop into rock. At 1.2 the threshold is 0.84:
  // the mountains' upper faces still go to stone, and the hill stays grass. The player's
  // real climb limit is read from PerspectiveScene directly and is not affected.
  static CLIMB_MAX_STEP = 1.2

  constructor(key = 'plates') {   // [introLevel] a subclass passes its own scene key
    super({ key })
    this.tileSize = 48   // matches the generated wallMask grid and Player's default
    const q = new URLSearchParams(window.location.search)
    this._keyMode = q.get('key') === '1'
    this._uiStartsHidden = q.get('ui') === '0'
    // [nightGrade] URL knobs, all optional. See the header.
    const num = (k) => { const v = parseFloat(q.get(k)); return Number.isFinite(v) ? v : null }
    this._night   = q.has('night')
      ? (q.get('night') === '' ? 1 : Math.max(0, Math.min(1, num('night') ?? 0)))
      : 0
    this._horizon = num('horizon')
    this._across  = num('across')
    // [bandMaps] which level, and its default horizon unless one was given
    const band = q.get('band')
    this._band = BANDS.includes(band) ? band : 'all'
    if (this._horizon == null) this._horizon = BAND_HORIZON[this._band]
    // [floraSwitch] null = the band's default (see getVegetation)
    const fl = q.get('flora')
    this._flora = fl === '1' ? true : fl === '0' ? false : null
  }

  getMapKey()  { return 'plates' }

  // [nightGrade] Per-scene renderer settings, the same mechanism the village uses.
  // Only what was asked for is changed; with no params this is the game's own config.
  getPGRConfig() {
    const cfg = super.getPGRConfig()
    if (this._horizon != null) cfg.HORIZON_Y_FRAC = Math.max(0.02, Math.min(0.45, this._horizon))
    if (this._across  != null) cfg.TILES_ACROSS    = Math.max(0.8,  Math.min(8,    this._across))
    return cfg
  }

  // The game eases the horizon and camera distance as tall terrain looms. For a
  // photograph that is just drift, so when the view has been set by hand it holds still.
  _updateCameraTerrainAvoidance() {
    if (this._horizon != null || this._across != null) return
    return super._updateCameraTerrainAvoidance()
  }
  // [bandMaps] plates.json is `all`; the others are plates_far / _mid / _near.
  getMapPath() {
    const file = this._band === 'all' ? 'plates' : `plates_${this._band}`
    return `/maps/bogMaps/${file}.json?v=${Date.now()}`
  }

  //  Collision: trees only 
  isColliding(x, y) {
    const tx = Math.floor(x / this.tileSize)
    const ty = Math.floor(y / this.tileSize)
    const mask = this.mapData?.wallMask
    if (!mask) return false
    if (ty < 0 || ty >= mask.length || tx < 0 || tx >= mask[0].length) return true
    return mask[ty][tx] >= 1
  }

  //  Look 
  // The game's own values for open ground (b1), so what is photographed is what
  // the player sees. In key mode the player's light comes off too: a bright
  // pool round the player would be baked into every screenshot.
  getAmbient()     { return 0x223322 }
  getPlayerLight() {
    return this._keyMode
      ? { color: 0xfff5dd, intensity: 0, radius: 1 }
      : { color: 0xfff5dd, intensity: 2.0, radius: 320 }
  }
  getWisps()      { return [] }
  getMusicTrack() { return null }

  getSkyImage()    { return this._keyMode ? null : '/assets/skies/bog_threshold_sky.png' }
  getSkyPosition() { return '50% 50%' }

  getTiltShift() {
    const base = super.getTiltShift()
    return this._keyMode ? { ...base, hazeAmount: 0, vignette: 0 } : base
  }

  // Ground flora on: this is where the near band's flowers come from. b0's values.
  getVegetation() {
    // [floraSwitch] Off unless asked for, except in the `all` preview. The near plate is
    // shot as bare ground: a screenshot freezes the flowers, and the intro will regrow them
    // live, so they keep the game's own sway. &flora=1 brings them back on any band.
    const on = this._flora ?? (this._band === 'all')
    if (!on) return false
    return { density: 0.34, clumpBias: 0.55, minScale: 22, heightTiles: 0.9 }
  }

  // PerspectiveScene's default _loadContent() is a no-op, which leaves
  // objects/npcs undefined and crashes the first update(). Nothing lives here.
  async _loadContent() {
    this.mapData.objects        = []
    this.mapData.npcs           = []
    this.mapData.introNarrative = []
  }

  onEnter() {
    console.log(`[plates] ready${this._keyMode ? ' (key mode)' : ''}${this._night ? ` night=${this._night}` : ''}`)
    // [bandMaps] The stone-face renderer is not automatic: only d3Sea and one test scene
    // create it. It paints grey stone on steep camera-facing slopes -- the mountains' upper
    // faces. It makes its own canvas (#steep-face-overlay), so it is made BEFORE the night
    // grade looks for layers to tint. Not needed on the flat near band.
    console.log(`[plates] band: ${this._band}${this._horizon != null ? ` horizon=${this._horizon}` : ''}`)
    if (this._band !== 'near') this.steepFaces = new SteepFaceRenderer(this)
    this.events.once('shutdown', () => {
      if (this.steepFaces) { this.steepFaces.destroy(); this.steepFaces = null }
    })
    this._applyNight()   // [nightGrade]

    // Chroma mode: nothing sits behind the world but the page, so the page is the key colour.
    if (this._keyMode) {
      document.documentElement.style.background = KEY_COLOUR
      document.body.style.background             = KEY_COLOUR
    }

    // A transparent hotspot, top-left. Tap it to hide or show the interface, so you can
    // walk about with the controls, then hide them for the shot. Fixed and above
    // everything, so it works while the interface is hidden.
    const hot = document.createElement('div')
    hot.id = 'plates-ui-toggle'
    hot.style.cssText = 'position:fixed;left:0;top:0;width:72px;height:72px;z-index:2147483647;background:transparent;'
    hot.addEventListener('pointerdown', (e) => { e.stopPropagation(); this._setUIHidden(!this._uiHidden) })
    document.body.appendChild(hot)
    this._uiHotspot = hot
    this.events.once('shutdown', () => { this._setUIHidden(false); hot.remove() })

    if (this._uiStartsHidden) this._setUIHidden(true)
  }

  // [bandMaps] Called by the ground renderer after every frame it draws.
  onPGRDrawComplete(ctx) {
    if (this.steepFaces) this.steepFaces.update()
  }

  // [nightGrade] An SVG filter on the WORLD layers -- not on the page, so the magenta
  // key colour behind them stays exactly magenta. `t` (0..1) blends every number from
  // "no change" to the full grade in NIGHT. The blur overlays sit above these layers, so
  // they blur the graded pixels.
  _applyNight() {
    const t = this._night
    if (!t) return
    const lerp  = (v) => 1 + (v - 1) * t
    const sat   = lerp(NIGHT.sat)
    const slope = NIGHT.slope.map(lerp)
    const lift  = NIGHT.lift.map(v => v * t)
    const NS = 'http://www.w3.org/2000/svg'
    const svg = document.createElementNS(NS, 'svg')
    svg.setAttribute('width', '0'); svg.setAttribute('height', '0')
    svg.style.cssText = 'position:absolute;width:0;height:0;pointer-events:none;'
    svg.innerHTML =
      `<filter id="plates-night" color-interpolation-filters="sRGB">` +
      `<feColorMatrix type="saturate" values="${sat.toFixed(4)}"/>` +
      `<feComponentTransfer>` +
      `<feFuncR type="linear" slope="${slope[0].toFixed(4)}" intercept="${lift[0].toFixed(4)}"/>` +
      `<feFuncG type="linear" slope="${slope[1].toFixed(4)}" intercept="${lift[1].toFixed(4)}"/>` +
      `<feFuncB type="linear" slope="${slope[2].toFixed(4)}" intercept="${lift[2].toFixed(4)}"/>` +
      `</feComponentTransfer></filter>`
    document.body.appendChild(svg)
    const layers = NIGHT_LAYERS.map(id => document.getElementById(id)).filter(Boolean)
    for (const el of layers) el.style.filter = 'url(#plates-night)'
    this.events.once('shutdown', () => {
      for (const el of layers) el.style.filter = ''
      svg.remove()
    })
  }

  // Hides or shows the interface for a clean screenshot: the joystick, the moon hub, the
  // fullscreen button, the status bar, everything the Phaser canvas draws (hearts,
  // badges), and the player. The Phaser canvas goes to opacity 0 rather than
  // display:none because it is also what receives taps for tap-to-walk.
  _setUIHidden(hidden) {
    this._uiHidden = hidden
    for (const id of ['status-bar', 'pgr-fullscreen-btn', 'dpad-root', 'dpad-moon-hub', 'dpad-fs-icon']) {
      document.querySelectorAll(`[id="${id}"]`).forEach(el => { el.style.visibility = hidden ? 'hidden' : '' })
    }
    if (this.game?.canvas) this.game.canvas.style.opacity = hidden ? '0' : ''

    // The player is drawn by the ground renderer from a canvas it rebuilds each frame.
    // Stop the rebuild and clear it; delete the override to bring the player back.
    const pgr = this.perspectiveGround
    if (pgr) {
      if (hidden) {
        pgr._refreshPlayerCanvas = () => { pgr._playerCanvas = null; pgr._playerFrameKey = null }
        pgr._playerCanvas = null
      } else {
        delete pgr._refreshPlayerCanvas
      }
      pgr.forceRedraw?.()
    }
  }
}
