// elevationMoatTest.js
// Location: js/game/scenes/locations/elevationMoatTest.js
//
// Test scene for a hill with a REAL VISIBLE cliff face, achieved by
// surrounding the steep sides with water so PGR's existing bank-face
// rendering fires (see elevation_moat_test_gen.mjs header for why water
// specifically, not steepness, is what triggers that code). Combined
// with slope-collision (engine-level, in perspectiveScene.js/player.js
// -- no per-scene code needed here) and the moat's own wallMask blocking
// entry into water, this is the first full test of: visible cliff +
// blocked climb + walkable ramp, together.
//
// No ForestEffects, no undergrowth, no trees -- deliberately bare, so
// this mechanic can be evaluated in true isolation, distinct from
// testForest's tree-driven organic hills.
//
// Map file: public/maps/forest/elevationMoatTest.json (generated by
// tools/map-editor/generators/elevation_moat_test_gen.mjs)

import PerspectiveScene from '../perspectiveScene.js'
import SteepFaceRenderer from '../../../effects/steepFaceRenderer.js'

export default class ElevationMoatTest extends PerspectiveScene {

  constructor() {
    super({ key: 'elevationMoatTest' })
    this.tileSize = 48
  }

  getMapKey()  { return 'elevationMoatTest' }
  getMapPath() { return `/maps/forest/cliffShowcase.json?v=${Date.now()}` }
onPGRDrawComplete() {
    if (this.steepFaces) this.steepFaces.update()
  }
  // Same wallMask-based collision pattern as testForest/elevationTest --
  // blocks the moat water and the map perimeter.
  isColliding(x, y) {
    const tx = Math.floor(x / this.tileSize)
    const ty = Math.floor(y / this.tileSize)
    const mask = this.mapData?.wallMask
    if (!mask) return false
    if (ty < 0 || ty >= mask.length || tx < 0 || tx >= mask[0].length) return true
    return mask[ty][tx] === 1
  }

  // Bright and undramatic on purpose -- this is a mechanic test, not a
  // mood piece. Nothing should be ambiguous because of lighting.
  getAmbient()     { return 0xcccccc }
  getPlayerLight() { return { color: 0xffffff, intensity: 1.0, radius: 200 } }
  getSkyImage()    { return null }
  getWisps()       { return [] }
  getMusicTrack()  { return null }

  async _loadContent() {
    this.mapData.objects        = []
    this.mapData.npcs           = []
    this.mapData.introNarrative = []
  }

	shutdown() {
    if (this.steepFaces) { this.steepFaces.destroy(); this.steepFaces = null }
    super.shutdown()
  }

  onEnter() {

	  this.steepFaces = new SteepFaceRenderer(this)
    console.log('[elevationMoatTest] ready -- walk north toward the hill, the gentle side should be a visible dry ramp, water should ring every other side')
  }
}
