// grove.js
// Location: js/game/scenes/locations/forest/grove.js
//
// ── Purpose ───────────────────────────────────────────────────────────────────
// PROTOTYPE. A small, purpose-built clearing/grove -- a pause-point space
// the player can rest in and see something at the centre from a distance,
// as a deliberate CONTRAST to testForest's dense maze. Built to test the
// "purpose first, then choose features" design direction: this map uses
// trunks + canopy + gentle elevation + LIGHT undergrowth accents, not the
// dense wall-to-wall obstacle coverage that made testForest read as
// cluttered once 3D undergrowth boxes were combined with trunks and
// canopy all at once.
//
// ── Design choices specific to this map ──────────────────────────────────────
//   • wallMask is SPARSE and intentional -- individually-spaced trees
//     ringing a clearing, not a maze. ForestEffects is constructed with
//     trunkKeepChance: 1.0 so EVERY wallMask cell gets a trunk (no
//     further thinning) -- the sparseness is already baked into the map
//     data itself, unlike testForest where thinning compensates for a
//     densely-authored wallMask.
//   • UndergrowthRenderer is constructed with keepChance/heightScale
//     turned down substantially for a much lighter presence, per
//     explicit direction: keep some undergrowth, but quiet.
//   • mapData.dolmenAnchor marks the centre tile where the dolmen
//     (DolmenRenderer) is constructed -- generated by gen_lagoon_map.py
//     alongside the pond/stepping-stones/asymmetric tree density. This
//     map is the dolmen's real home, not a temporary test placement.
//
// Map file: public/maps/forest/grove.json

import PerspectiveScene from '../perspectiveScene.js'
import ForestEffects from '../../../effects/forestEffects.js'
import UndergrowthRenderer from '../../../effects/undergrowthRenderer.js'
import DolmenRenderer from '../../../effects/dolmenRenderer.js'

export default class Grove extends PerspectiveScene {

  constructor() {
    super({ key: 'grove' })
    this.tileSize = 48
  }

  getMapKey() { return 'grove' }
  getMapPath() { return `/maps/forest/${this.getMapKey()}.json?v=${Date.now()}` }

  // No real wall collision data beyond wallMask-driven trunks for now --
  // same temporary all-walkable debug stance as testForest, kept
  // consistent rather than introducing a different collision behaviour
  // between the two forest prototypes while both are still in flux.
  isColliding(x, y) {
    return false
  }

  // Slightly more open than testForest's tight maze framing -- this is a
  // clearing meant to be SEEN across, not a claustrophobic corridor, so
  // the field of view is a little wider. Still close/over-the-shoulder
  // per the established camera direction (not revisiting camera choice
  // here, per earlier discussion that camera position is fine for now).
  getPGRConfig() {
    return {
      ...super.getPGRConfig(),
      TILES_ACROSS:      3.0,    // wider than testForest's 2.4 -- see across the clearing
      CAMERA_ROW_OFFSET: 9.0,
      FOCAL_LENGTH:      9.0,    // slightly less tight than testForest's 8.0
    }
  }

  getAmbient() { return 0x141810 }   // slightly lighter than testForest's near-black --
                                       // this is a calmer space, not oppressive gloom

  getPlayerLight() {
    return { color: 0xffe0a0, intensity: 1.2, radius: 160 }
  }

  getSkyImage() { return null }
  getWisps()      { return [] }
  getMusicTrack() { return null }
  usesSwallows()  { return false }   // same pattern as BogD3Sea -- swallows
                                       // don't fit a dense forest/pond interior

  async _loadContent() {
    this.mapData.objects        = []
    this.mapData.npcs           = []
    this.mapData.introNarrative = []
  }

  onEnter() {
    console.log('[grove] prototype scene ready -- sparse trees, light undergrowth, clear centre sightline')
    console.log('[grove] dolmen anchor at', this.mapData?.dolmenAnchor)

    // trunkKeepChance: 1.0 -- every wallMask cell gets a trunk. The
    // grove's wallMask is ALREADY sparse by design (individually-spaced
    // trees from gen_grove_map.py), unlike testForest's dense maze where
    // the default 0.45 thinning compensates for every-other-cell
    // coverage. Applying that same thinning here would make an already
    // sparse layout even sparser than intended.
    this.forestEffects = new ForestEffects(this, { trunkKeepChance: 1.0 })

    // Light undergrowth: keepChance thins WHICH wallMask cells get an
    // obstacle box at all (0.35 -- roughly a third), heightScale shrinks
    // every kind's height substantially (0.5 -- about half) for a
    // quieter, accent-level presence rather than testForest's full
    // density/height, which combined with trunks+canopy read as
    // cluttered. Tune both further once seen in-engine.
    this.forestEffects.undergrowthRenderer = new UndergrowthRenderer(
      this, this.forestEffects.ctx, { keepChance: 0.35, heightScale: 0.5 }
    )

    // The dolmen's real home -- generated by gen_lagoon_map.py and
    // recorded as mapData.dolmenAnchor (centre of the pond, where
    // stepping stones lead). No longer a temporary test placement.
    const anchor = this.mapData?.dolmenAnchor
    if (anchor) {
      this.dolmen = new DolmenRenderer(this, this.forestEffects.ctx, {
        anchorX: anchor.x, anchorY: anchor.y
      })
    }

    this.events.once('shutdown', () => {
      console.log('[grove] real shutdown EVENT fired -- cleaning up forestEffects')
      if (this.dolmen) { this.dolmen.destroy(); this.dolmen = null }
      if (this.forestEffects?.undergrowthRenderer) {
        this.forestEffects.undergrowthRenderer.destroy()
        this.forestEffects.undergrowthRenderer = null
      }
      if (this.forestEffects) { this.forestEffects.destroy(); this.forestEffects = null }
    })
  }

  // See TestForest's identical method for the full explanation -- PGR's
  // idle-redraw-skip optimization (8s battery saver) was silently
  // freezing canopy sway whenever the player stood still. This opts
  // grove out of that skip.
  hasContinuousAnimation() { return true }

  onPGRDrawComplete() {
    if (!this.forestEffects) return

    if (!this.dolmen || !this.perspectiveGround) {
      // No dolmen to interleave with -- normal single-pass draw.
      this.forestEffects.update()
      return
    }

    // Real depth-sorting against the dolmen: trunks were previously
    // ALWAYS drawn before the dolmen, so the dolmen always rendered on
    // top regardless of actual depth -- wrong once trees stood near/in
    // front of it from the camera's POV (confirmed via screenshot: a
    // tree rendering behind the dolmen when it should have occluded
    // part of it). Fixed by splitting trunk drawing into two passes
    // around the dolmen's own row: trunks further from the camera than
    // the dolmen draw FIRST (so the dolmen can cover them), then the
    // dolmen itself, then trunks closer to the camera than the dolmen
    // draw LAST (so they correctly cover the dolmen). This engine's
    // camera looks toward decreasing row, so "row < dolmenRow" is
    // farther away (behind), "row >= dolmenRow" is closer (in front) --
    // same convention ForestEffects' own south-of-player trunk fade
    // already uses.
    const dolmenRow = this.mapData?.dolmenAnchor?.y ?? 0

    this.forestEffects.update(true)   // skipTrunks=true -- tint/undergrowth/haze only
    this.forestEffects.drawTrunksInRowRange(this.perspectiveGround, (ty) => ty < dolmenRow)
    this.dolmen.update(this.perspectiveGround, this.forestEffects._sw, this.forestEffects._sh)
    this.forestEffects.drawTrunksInRowRange(this.perspectiveGround, (ty) => ty >= dolmenRow)
    this.forestEffects.punchPlayerHoleNow(this.perspectiveGround)
  }

  shutdown() {
    console.log('[grove] shutdown() method called -- forestEffects present:', !!this.forestEffects)
    if (this.forestEffects?.undergrowthRenderer) {
      this.forestEffects.undergrowthRenderer.destroy()
      this.forestEffects.undergrowthRenderer = null
    }
    if (this.forestEffects) { this.forestEffects.destroy(); this.forestEffects = null }
    super.shutdown()
  }
}

