// testForest.js
// Location: js/game/scenes/locations/forest/testForest.js
//
// Open forest test scene. Trees (from wallMask, scatter-generated) are
// the only blocking element -- no maze walls. UndergrowthRenderer adds
// non-blocking floor decoration (ferns/grass/flowers as billboards,
// sparse slope-gated rocks) -- purely visual, does not affect collision.
// Canopy is handled entirely by ForestEffects' foliage caps.
//
// Map file: public/maps/forest/testForest.json (generated by
// tools/map-editor/generators/forest_scatter_gen.mjs)

import PerspectiveScene from '../perspectiveScene.js'
import ForestEffects from '../../../effects/forestEffects.js'
import UndergrowthRenderer from '../../../effects/undergrowthRenderer.js'

export default class TestForest extends PerspectiveScene {

  constructor() {
    super({ key: 'testForest' })
    this.tileSize = 48   // must match Player's default and wallMask's authored grid
  }

  getMapKey() { return 'testForest' }

  // Map lives in public/maps/forest/, not the inherited default
  // (/maps/bogMaps/${key}.json) -- forest maps get their own folder.
  getMapPath() { return `/maps/forest/${this.getMapKey()}.json?v=${Date.now()}` }

  // ── Collision ─────────────────────────────────────────────────────────────
  // Real wallMask check -- trees are the only blocking cells. Undergrowth
  // is drawn separately and never touches this.
  isColliding(x, y) {
    const tx = Math.floor(x / this.tileSize)
    const ty = Math.floor(y / this.tileSize)
    const mask = this.mapData?.wallMask
    if (!mask) return false
    if (ty < 0 || ty >= mask.length || tx < 0 || tx >= mask[0].length) return true
    return mask[ty][tx] >= 1
  }

  // ── Camera: close / over-the-shoulder ─────────────────────────────────────
  // Overworld default (from BaseLocationScene) is TILES_ACROSS: 3.8 -- showing
  // ~4 tiles of width. Tightening this zooms in. CAMERA_ROW_OFFSET pulls the
  // camera closer behind the player; FOCAL_LENGTH shorter = more fisheye/close
  // feel. These are first-guess numbers -- expect to tune by eye in-engine.
  getPGRConfig() {
    return {
      ...super.getPGRConfig(),
      TILES_ACROSS:      2.4,   // was 3.8 -- zoom in, narrower field of view
      CAMERA_ROW_OFFSET: 9.0,   // was 14.0 -- camera sits closer behind player
      FOCAL_LENGTH:      8.0,   // was 12.0 -- tighter, more claustrophobic
      // HORIZON_Y_FRAC and HEIGHT_MULTIPLIER left at overworld defaults
      // (via super.getPGRConfig()) -- canopy looming is ForestEffects' job,
      // layered above PGR, not baked into ground-renderer billboards.
    }
  }

  // ── Mood: gloom under canopy ───────────────────────────────────────────────
  // Dark ambient + small warm player light = "your own light is small against
  // the dark." No sky image -- canopy blocks it entirely (PGR falls back to
  // flat ground colour when getSkyImage() returns null).
  getAmbient() { return 0x0a0c08 }

  getPlayerLight() {
    return { color: 0xffcc88, intensity: 1.1, radius: 140 }
  }

  getSkyImage() { return null }

  getWisps()      { return [] }
  getMusicTrack() { return null }

  // PerspectiveScene's default _loadContent() is a no-op, which leaves
  // mapData.objects/npcs as undefined. createObjects() guards on that and
  // returns early WITHOUT setting this.interactables = [], so the very next
  // update() crashes in checkProximityInteractions() on undefined.forEach.
  // Explicitly initialize both to empty arrays until real content exists.
  async _loadContent() {
    this.mapData.objects        = []
    this.mapData.npcs           = []
    this.mapData.introNarrative = []
  }

  onEnter() {
    console.log('[testForest] open scatter forest ready')
    // PGR exists by the time onEnter() fires (create() builds it earlier
    // in drawTilemap()). Construct the canopy overlay now.
    this.forestEffects = new ForestEffects(this)

    // Undergrowth shares ForestEffects' own canvas context (via its `ctx`
    // getter) rather than creating a second DOM canvas layer --
    // ForestEffects.update() already has a no-op-safe hook
    // (this.undergrowthRenderer) that calls .update(pgr, sw, sh) on
    // whatever's assigned here, at the right point in the draw order.
    this.forestEffects.undergrowthRenderer = new UndergrowthRenderer(this, this.forestEffects.ctx)

    // IMPORTANT: Phaser dispatches 'shutdown' as an EVENT through
    // this.events -- it does NOT automatically invoke a plain method
    // literally named shutdown() on the Scene instance. Confirmed via
    // Phaser docs (Scenes.Events.SHUTDOWN). Wiring the real event here
    // as a belt-and-suspenders fix alongside the plain override below.
    this.events.once('shutdown', () => {
      console.log('[testForest] real shutdown EVENT fired -- cleaning up forestEffects')
      if (this.forestEffects?.undergrowthRenderer) {
        this.forestEffects.undergrowthRenderer.destroy()
        this.forestEffects.undergrowthRenderer = null
      }
      if (this.forestEffects) { this.forestEffects.destroy(); this.forestEffects = null }
    })
  }

  // Tells PGR's idle-redraw-skip optimization (an 8-second battery-saving
  // early-return when player/camera are stationary) that this scene has
  // continuous animation that must keep running regardless -- canopy
  // sway (ForestEffects) animates via performance.now() every frame and
  // was silently freezing whenever the player stood still for 8+ seconds.
  hasContinuousAnimation() { return true }

  // PGR calls this.scene?.onPGRDrawComplete?.(ctx) at the very end of its own
  // update(), every frame -- this is the hook PerspectiveScene's update()
  // loop already provides without us needing to override update() ourselves.
  // ForestEffects.update() reads pgr.playerScreenX/Y, which are guaranteed
  // current by this point in the frame since PGR just finished setting them.
  onPGRDrawComplete() {
    if (this.forestEffects) this.forestEffects.update()
  }

  // Kept as a plain method override too, in case it DOES also get invoked
  // in some code path -- harmless either way since forestEffects is
  // nulled after first cleanup, so a second call here is a no-op.
  shutdown() {
    console.log('[testForest] shutdown() method called -- forestEffects present:', !!this.forestEffects)
    if (this.forestEffects?.undergrowthRenderer) {
      this.forestEffects.undergrowthRenderer.destroy()
      this.forestEffects.undergrowthRenderer = null
    }
    if (this.forestEffects) { this.forestEffects.destroy(); this.forestEffects = null }
    super.shutdown()
  }
}
